spring:
  profiles: default
  
  jpa:
    hibernate:
      ddl-auto: create-update
    generate-ddl: false
    show-sql: true
    
datasource:
    masterDB:
       driver-class-name: "com.mysql.jdbc.Driver"
       url: "jdbc:mysql://52.78.110.20:3306/gamseong?useUnicode=true&characterEncoding=UTF-8"
       username: 'root'
       password: gamseong1234
       initial-size: 10
       max-active: 10
       max-idle: 10
       min-idle: 10
       max-wait: 3000
    slaveDB:
       driver-class-name: "com.mysql.jdbc.Driver"
       url: "jdbc:mysql://52.78.110.20:3306/gamseong?useUnicode=true&characterEncoding=UTF-8"
       username: 'root'
       password: gamseong1234
       initial-size: 10
       max-active: 10
       max-idle: 10
       min-idle: 10
       max-wait: 3000
      

    